/*
Statement failed, SQLSTATE = 42000
ALTER PROCEDURE DFL_MVPRODUTO failed
-Dynamic SQL Error
-SQL error code = -637
-duplicate specification of ESTOQUEGERAL - not supported
After line 166473 in file .\firebird-v3\scgwin\bancos\saul-matriz\metadados.sql
*/

SET TERM ^ ;

ALTER PROCEDURE DFL_MVPRODUTO (EEMAIL VARCHAR(100) CHARACTER SET ISO8859_1)
RETURNS (CODPRODFILHO INTEGER,
DESCRICAO VARCHAR(60) CHARACTER SET ISO8859_1,
REFERENCIA VARCHAR(30) CHARACTER SET ISO8859_1,
GTIN VARCHAR(30) CHARACTER SET ISO8859_1,
APRESENTACAO VARCHAR(15) CHARACTER SET ISO8859_1,
CODUNIDADE INTEGER,
UNIDADE VARCHAR(5) CHARACTER SET ISO8859_1,
TRAVA_FRACIONADO VARCHAR(1) CHARACTER SET ISO8859_1,
PRECOVENDA1 NUMERIC(15, 2),
PRECOVENDA2 NUMERIC(15, 2),
PRECOVENDA3 NUMERIC(15, 2),
PRECOVENDA4 NUMERIC(15, 2),
PRECOVENDA5 NUMERIC(15, 2),
PRECOVENDA6 NUMERIC(15, 2),
ESTQATUAL NUMERIC(15, 3),
CODFABRICANTE INTEGER,
FABRICANTE VARCHAR(60) CHARACTER SET ISO8859_1,
CODGRUPO INTEGER,
DESCGRUPO VARCHAR(60) CHARACTER SET ISO8859_1,
CODSUBGRUPO INTEGER,
DESCSUBGRUPO VARCHAR(60) CHARACTER SET ISO8859_1,
DESCONTFLAG SMALLINT,
DESCONTDESEJ NUMERIC(15, 4),
QTDMULTPLA DOUBLE PRECISION,
ESTOQUELOJA DOUBLE PRECISION,
ESTOQUEGERAL DOUBLE PRECISION,
ESTOQUEDEPOSITO DOUBLE PRECISION,
FOTO BLOB)
AS 
DECLARE VARIABLE PARTABELA_DE_PRECO_MINIMO SMALLINT;
DECLARE VARIABLE LCODUSERCAD INTEGER;
DECLARE VARIABLE LCODEMPRESA INTEGER;
DECLARE VARIABLE LCODEMPRESADEPOSITO INTEGER;
DECLARE "C_ESTOQUEGERAL" CURSOR FOR (
    SELECT SUM(P.QTD) QUANTIDADE
    FROM PRODFILHOLOTES P
    WHERE P.CODPRODFILHO = :CODPRODFILHO);
DECLARE "ESTOQUEDEPOSITO" CURSOR FOR (
    SELECT SUM(P.QTD) QUANTIDADE
    FROM PRODFILHOLOTES P
    JOIN LOTE ON P.LOTE = LOTE.DESCRICAO AND
          LOTE.CODEMPRESA = :LCODEMPRESADEPOSITO
    WHERE P.CODPRODFILHO = :CODPRODFILHO);
DECLARE "ESTOQUELOJA" CURSOR FOR (
    SELECT SUM(P.QTD) QUANTIDADE
    FROM PRODFILHOLOTES P
    JOIN LOTE ON P.LOTE = LOTE.DESCRICAO AND
          LOTE.CODEMPRESA = :LCODEMPRESA
    WHERE P.CODPRODFILHO = :CODPRODFILHO);
BEGIN
  SELECT CODUSERCAD, CODEMPRESA  FROM USERCAD WHERE EMAIL = :EEMAIL INTO LCODUSERCAD, LCODEMPRESA;    
  SELECT VALOR FROM MLERPARAMETROINTEIRO('EMPRESA PADRÃO DEPOSITO',0) INTO LCODEMPRESADEPOSITO;
   
  PARTABELA_DE_PRECO_MINIMO = 6;
  FOR SELECT
    PRODFILHO.CODPRODFILHO,
    PRODFILHO.DESCRICAO,
    COALESCE(PRODFILHO.CODPESQ1,'') REFERENCIA,
    COALESCE(PRODFILHO.CODPESQ2,'') GTIN,
    COALESCE(PRODFILHO.UNIDADE, UNIDADE.SIGLA) APRESENTACAO,
    PRODFILHO.CODUNIDADE,
    UNIDADE.SIGLA UNIDADE,
    COALESCE(UNIDADE.TRAVA_FRACIONADO,'N'),
    CAST(COALESCE(PRODFILHO.PRECOPRATICADO1,0) AS NUMERIC(15,2)) PRECOVENDA1,
    CAST(COALESCE(PRODFILHO.PRECOPRATICADO2,0) AS NUMERIC(15,2)) PRECOVENDA2,
    CAST(COALESCE(PRODFILHO.PRECOPRATICADO3,0) AS NUMERIC(15,2)) PRECOVENDA3,
    CAST(COALESCE(PRODFILHO.PRECOPRATICADO4,0) AS NUMERIC(15,2)) PRECOVENDA4,
    CAST(COALESCE(PRODFILHO.PRECOPRATICADO5,0) AS NUMERIC(15,2)) PRECOVENDA5,
    CAST(COALESCE(PRODFILHO.PRECOPRATICADO6,0) AS NUMERIC(15,2)) PRECOVENDA6,
    CAST(COALESCE(PRODFILHO.ESTQATUAL,0) AS NUMERIC(15,3)),
    COALESCE(PRODUTO.CODFABRICANTE,0),
    COALESCE((SELECT COALESCE(NOME,'') FROM PESSOA WHERE PESSOA.CODPESSOA = PRODUTO.CODFABRICANTE),'') FABRICANTE,
    PRODUTO.CODGRUPO,
    GRUPO.DESCRICAO DESCGRUPO,
    PRODUTO.CODSUBGRUPO,
    SUBGRUPO.DESCRICAO DESCSUBGRUPO,
    COALESCE(PRODFILHO.DESCONTFLAG,1) DESCONTFLAG,
    COALESCE(PRODFILHO.DESCONTDESEJ,0) DESCONTDESEJ,    
    COALESCE(PRODFILHO.QTDMULTPLA,0)
  FROM
    PRODUTO
    JOIN PRODFILHO ON
      PRODUTO.CODPRODUTO = PRODFILHO.CODPRODUTO
    JOIN UNIDADE ON
      PRODFILHO.CODUNIDADE = UNIDADE.CODUNIDADE
    JOIN GRUPO ON
      PRODUTO.CODGRUPO = GRUPO.CODGRUPO
    JOIN SUBGRUPO ON
      PRODUTO.CODSUBGRUPO = SUBGRUPO.CODSUBGRUPO
  WHERE 
    PRODUTO.ATIVO = 2
  ORDER BY
    PRODFILHO.DESCRICAO
  INTO
    CODPRODFILHO,
    DESCRICAO,
    REFERENCIA,
    GTIN,
    APRESENTACAO,
    CODUNIDADE,
    UNIDADE,
    TRAVA_FRACIONADO,
    PRECOVENDA1,
    PRECOVENDA2,
    PRECOVENDA3,
    PRECOVENDA4,
    PRECOVENDA5,
    PRECOVENDA6,
    ESTQATUAL,
    CODFABRICANTE,
    FABRICANTE,
    CODGRUPO,
    DESCGRUPO,
    CODSUBGRUPO,
    DESCSUBGRUPO,
    DESCONTFLAG,
    DESCONTDESEJ,
    QTDMULTPLA
  DO
  BEGIN      

    OPEN "ESTOQUELOJA";
    WHILE (1=1) DO
    BEGIN
      FETCH "ESTOQUELOJA" INTO ESTOQUELOJA;
      IF (ROW_COUNT = 0) THEN LEAVE;
    END
    CLOSE "ESTOQUELOJA";

    ESTOQUELOJA = COALESCE(ESTOQUELOJA,0);
  
    OPEN "ESTOQUEDEPOSITO";
    WHILE (1=1) DO
    BEGIN
      FETCH "ESTOQUEDEPOSITO" INTO ESTOQUEDEPOSITO;
      IF (ROW_COUNT = 0) THEN LEAVE;
    END
    CLOSE "ESTOQUEDEPOSITO";
  
    ESTOQUEDEPOSITO = COALESCE(ESTOQUEDEPOSITO,0);

    OPEN "C_ESTOQUEGERAL";
    WHILE (1=1) DO
    BEGIN
      FETCH "C_ESTOQUEGERAL" INTO ESTOQUEGERAL;
      IF (ROW_COUNT = 0) THEN LEAVE;
    END
    CLOSE "C_ESTOQUEGERAL";

    ESTOQUEGERAL = COALESCE(ESTOQUEGERAL,0);

    FOTO = NULL;
    SELECT FOTO FROM DFL_MVPRODUTOFOTO(:CODPRODFILHO) INTO  FOTO;
  
    SUSPEND;
  END
END ^

SET TERM ; ^

/*
Statement failed, SQLSTATE = 07001
unsuccessful metadata update
-ALTER PROCEDURE SPNFENTRADAITENSLIBERACAO failed
-Dynamic SQL Error
-Input parameter mismatch for procedure STP_MKP_FORMULA_CUSTOFAT
After line 401771 in file .\firebird-v3\scgwin\bancos\saul-matriz\metadados.sql
*/

SET TERM ^ ;

ALTER PROCEDURE SPNFENTRADAITENSLIBERACAO (ECODNFENTRADA INTEGER)
RETURNS (CODNFENTRADAITENS INTEGER,
CODNFENTRADA INTEGER,
CODPRODFILHO INTEGER,
CODPESQUISA VARCHAR(30) CHARACTER SET ISO8859_1,
CODPEDCPR INTEGER,
CODPEDCPRITENS INTEGER,
XPEDIDO VARCHAR(15) CHARACTER SET ISO8859_1,
NITEMPED VARCHAR(6) CHARACTER SET ISO8859_1,
CUSTOREPOSI DOUBLE PRECISION,
CUSTOREPOSIPROD DOUBLE PRECISION,
CUSTOMEDIOPROD DOUBLE PRECISION,
CUSTOMEDIOATUAL DOUBLE PRECISION,
CUSTOCALCULADO DOUBLE PRECISION,
PRODVLR DOUBLE PRECISION,
QTD DOUBLE PRECISION,
TOTALPROD NUMERIC(18, 2),
DESCTO_ITEM_PERC DOUBLE PRECISION,
DESCTO_ITEM DOUBLE PRECISION,
IPIPERC DOUBLE PRECISION,
VL_IPIPERC DOUBLE PRECISION,
BASE_ICMS DOUBLE PRECISION,
DIFICMS DOUBLE PRECISION,
PERC_REDUCAO DOUBLE PRECISION,
REDUCAO_VALOR DOUBLE PRECISION,
VL_DIFICMS DOUBLE PRECISION,
FRETEPERCLTDA DOUBLE PRECISION,
FRETEVLRLTDA DOUBLE PRECISION,
DESP_PERC DOUBLE PRECISION,
DESP_VALOR DOUBLE PRECISION,
SEG_PERC DOUBLE PRECISION,
SEG_VALOR DOUBLE PRECISION,
PERC_VA DOUBLE PRECISION,
VA_VALOR DOUBLE PRECISION,
PREDUCAOST DOUBLE PRECISION,
VREDUCAOST DOUBLE PRECISION,
BASE_SUBS DOUBLE PRECISION,
ALIQ_SUBS DOUBLE PRECISION,
VALOR_SUBS DOUBLE PRECISION,
VALORTOTAL DOUBLE PRECISION,
TOTAL_NOTA DOUBLE PRECISION,
MARKUP1 DOUBLE PRECISION,
MARKUP2 DOUBLE PRECISION,
MARKUP3 DOUBLE PRECISION,
MARKUP4 DOUBLE PRECISION,
MARKUP5 DOUBLE PRECISION,
MARKUP6 DOUBLE PRECISION,
MARKUPPROD1 DOUBLE PRECISION,
MARKUPPROD2 DOUBLE PRECISION,
MARKUPPROD3 DOUBLE PRECISION,
MARKUPPROD4 DOUBLE PRECISION,
MARKUPPROD5 DOUBLE PRECISION,
MARKUPPROD6 DOUBLE PRECISION,
PRECOPRATICADO1 DOUBLE PRECISION,
PRECOPRATICADO2 DOUBLE PRECISION,
PRECOPRATICADO3 DOUBLE PRECISION,
PRECOPRATICADO4 DOUBLE PRECISION,
PRECOPRATICADO5 DOUBLE PRECISION,
PRECOPRATICADO6 DOUBLE PRECISION,
PRECOPRATICADOPROD1 DOUBLE PRECISION,
PRECOPRATICADOPROD2 DOUBLE PRECISION,
PRECOPRATICADOPROD3 DOUBLE PRECISION,
PRECOPRATICADOPROD4 DOUBLE PRECISION,
PRECOPRATICADOPROD5 DOUBLE PRECISION,
PRECOPRATICADOPROD6 DOUBLE PRECISION,
PRECOSUGERIDO1 DOUBLE PRECISION,
PRECOSUGERIDO2 DOUBLE PRECISION,
PRECOSUGERIDO3 DOUBLE PRECISION,
PRECOSUGERIDO4 DOUBLE PRECISION,
PRECOSUGERIDO5 DOUBLE PRECISION,
PRECOSUGERIDO6 DOUBLE PRECISION,
DESCRICAO VARCHAR(60) CHARACTER SET ISO8859_1,
CUSTO_VALOR_CALCULADO DOUBLE PRECISION,
ALIQUOTAICMS DOUBLE PRECISION,
PERC_PIS DOUBLE PRECISION,
PERC_COFINS DOUBLE PRECISION,
PERC_CSLL DOUBLE PRECISION,
PERC_IMPOSTORENDA DOUBLE PRECISION,
PERCMVOUTROS DOUBLE PRECISION,
ALIQCOMISSAO DOUBLE PRECISION,
ALIQCOMISSAO_APOIO DOUBLE PRECISION,
PERC_DESPESAS_FIXAS DOUBLE PRECISION,
PERC_CALCULADO DOUBLE PRECISION,
MARKUPREAL1 DOUBLE PRECISION,
MARKUPREAL2 DOUBLE PRECISION,
MARKUPREAL3 DOUBLE PRECISION,
MARKUPREAL4 DOUBLE PRECISION,
MARKUPREAL5 DOUBLE PRECISION,
MARKUPREAL6 DOUBLE PRECISION,
CUSTOMEDIOCALCULADO DOUBLE PRECISION,
ESTOQATUAL DOUBLE PRECISION,
FRETEAVULSO DOUBLE PRECISION,
PRECOCAT DOUBLE PRECISION,
CODPRODUTO INTEGER,
IDNFENTRADAITEM VARCHAR(40) CHARACTER SET ISO8859_1,
DESPFRONTPERCITEM DOUBLE PRECISION,
DESPFRONTVLRITEM DOUBLE PRECISION,
CUSTOREPOSI2 DOUBLE PRECISION,
CODUNIDADE INTEGER,
PRECOCOMPRAANTERIOR DOUBLE PRECISION,
DESPESAS DOUBLE PRECISION,
COMISSAO DOUBLE PRECISION,
ACRESCIMO DOUBLE PRECISION)
AS 
declare variable LPRECOSUGERIDO1 double precision;
declare variable LPRECOSUGERIDO2 double precision;
declare variable LPRECOSUGERIDO3 double precision;
declare variable LPRECOSUGERIDO4 double precision;
declare variable LPRECOSUGERIDO5 double precision;
declare variable LPRECOSUGERIDO6 double precision;
declare variable LMARKUP1 double precision;
declare variable LMARKUP2 double precision;
declare variable LMARKUP3 double precision;
declare variable LMARKUP4 double precision;
declare variable LMARKUP5 double precision;
declare variable LMARKUP6 double precision;
declare variable LVALORPIS double precision;
declare variable LVALORCOFINS double precision;
declare variable LSQL blob sub_type 1 segment size 80;
BEGIN

  if (exists(select 1 from CONSULTA_CUSTOMIZADA where CONSULTA_CUSTOMIZADA.CONSULTA = 'SPNFENTRADAITENSLIBERACAO')) then
  begin
    select SQL from CONSULTA_CUSTOMIZADA where CONSULTA_CUSTOMIZADA.CONSULTA = 'SPNFENTRADAITENSLIBERACAO' into LSQL;
    for execute statement (LSQL)
    (
      ECODNFENTRADA := :ECODNFENTRADA
    )
    into
    CODNFENTRADAITENS,
    CODNFENTRADA,
    CODPRODFILHO,
    CODPESQUISA,
    CODPEDCPR,
    CODPEDCPRITENS,
    XPEDIDO,
    NITEMPED,
    CUSTOREPOSI,
    CUSTOREPOSIPROD,
    CUSTOMEDIOPROD,
    CUSTOMEDIOATUAL,
    CUSTOCALCULADO,
    PRODVLR,
    QTD,
    TOTALPROD,
    DESCTO_ITEM_PERC,
    DESCTO_ITEM,
    IPIPERC,
    VL_IPIPERC,
    BASE_ICMS,
    DIFICMS,
    PERC_REDUCAO,
    REDUCAO_VALOR,
    VL_DIFICMS,
    FRETEPERCLTDA,
    FRETEVLRLTDA,
    DESP_PERC,
    DESP_VALOR ,
    SEG_PERC,
    SEG_VALOR,
    PERC_VA,
    VA_VALOR,
    PREDUCAOST,
    VREDUCAOST,
    BASE_SUBS,
    ALIQ_SUBS,
    VALOR_SUBS,
    VALORTOTAL,
    TOTAL_NOTA,
    MARKUP1,
    MARKUP2,
    MARKUP3,
    MARKUP4,
    MARKUP5,
    MARKUP6,
    MARKUPPROD1,
    MARKUPPROD2,
    MARKUPPROD3,
    MARKUPPROD4,
    MARKUPPROD5,
    MARKUPPROD6,
    PRECOPRATICADO1,
    PRECOPRATICADO2,
    PRECOPRATICADO3,
    PRECOPRATICADO4,
    PRECOPRATICADO5,
    PRECOPRATICADO6,
    PRECOPRATICADOPROD1,
    PRECOPRATICADOPROD2,
    PRECOPRATICADOPROD3,
    PRECOPRATICADOPROD4,
    PRECOPRATICADOPROD5,
    PRECOPRATICADOPROD6,
    PRECOSUGERIDO1,
    PRECOSUGERIDO2,
    PRECOSUGERIDO3,
    PRECOSUGERIDO4,
    PRECOSUGERIDO5,
    PRECOSUGERIDO6,
    DESCRICAO,
    CUSTO_VALOR_CALCULADO,
    ALIQUOTAICMS,
    PERC_PIS,
    PERC_COFINS,
    PERC_CSLL,
    PERC_IMPOSTORENDA,
    PERCMVOUTROS,
    ALIQCOMISSAO,
    ALIQCOMISSAO_APOIO,
    PERC_DESPESAS_FIXAS,
    PERC_CALCULADO,
    MARKUPREAL1,
    MARKUPREAL2,
    MARKUPREAL3,
    MARKUPREAL4,
    MARKUPREAL5,
    MARKUPREAL6,
    CUSTOMEDIOCALCULADO,
    ESTOQATUAL,
    FRETEAVULSO,
    PRECOCAT,
    CODPRODUTO,
    IDNFENTRADAITEM,
    DESPFRONTPERCITEM,
    DESPFRONTVLRITEM,
    CUSTOREPOSI2,
    CODUNIDADE,
    PRECOCOMPRAANTERIOR,
    DESPESAS,
    COMISSAO,
    ACRESCIMO
    do
    begin
      suspend;
    end
    exit;
  end


  FOR SELECT
    NFENTRADAITENS.CODNFENTRADAITENS,
    NFENTRADAITENS.CODNFENTRADA,
    NFENTRADAITENS.CODPRODFILHO,
    NFENTRADAITENS.CODPESQUISA,
    NFENTRADAITENS.CODPEDCPR,
    NFENTRADAITENS.CODPEDCPRITENS,
    NFENTRADAITENS.XPEDIDO,
    NFENTRADAITENS.NITEMPED,
    NFENTRADAITENS.PRODVLR,
    NFENTRADAITENS.QTD,
    NFENTRADAITENS.TOTALPROD,
    NFENTRADAITENS.DESCTO_ITEM_PERC,
    NFENTRADAITENS.DESCTO_ITEM,
    NFENTRADAITENS.IPIPERC,
    NFENTRADAITENS.VL_IPIPERC,
    NFENTRADAITENS.BASE_ICMS,
    NFENTRADAITENS.DIFICMS,
    NFENTRADAITENS.PERC_REDUCAO,
    NFENTRADAITENS.REDUCAO_VALOR,
    NFENTRADAITENS.VL_DIFICMS,
    NFENTRADAITENS.FRETEPERCLTDA,
    NFENTRADAITENS.FRETEVLRLTDA,
    NFENTRADAITENS.DESP_PERC,
    NFENTRADAITENS.DESP_VALOR,
    NFENTRADAITENS.SEG_PERC,
    NFENTRADAITENS.SEG_VALOR,
    NFENTRADAITENS.PERC_VA,
    NFENTRADAITENS.VA_VALOR,
    NFENTRADAITENS.PREDUCAOST,
    NFENTRADAITENS.VREDUCAOST,
    NFENTRADAITENS.BASE_SUBS,
    NFENTRADAITENS.ALIQ_SUBS,
    NFENTRADAITENS.VALOR_SUBS,
    NFENTRADAITENS.VALORTOTAL,
    NFENTRADAITENS.TOTAL_NOTA,
    COALESCE(NFENTRADAITENS.MARKUP1,0) MARKUP1,
    COALESCE(NFENTRADAITENS.MARKUP2,0) MARKUP2,
    COALESCE(NFENTRADAITENS.MARKUP3,0) MARKUP3,
    COALESCE(NFENTRADAITENS.MARKUP4,0) MARKUP4,
    COALESCE(NFENTRADAITENS.MARKUP5,0) MARKUP5,
    COALESCE(NFENTRADAITENS.MARKUP6,0) MARKUP6,
    COALESCE(NFENTRADAITENS.PRECOPRATICADO1,0) PRECOPRATICADO1,
    COALESCE(NFENTRADAITENS.PRECOPRATICADO2,0) PRECOPRATICADO2,
    COALESCE(NFENTRADAITENS.PRECOPRATICADO3,0) PRECOPRATICADO3,
    COALESCE(NFENTRADAITENS.PRECOPRATICADO4,0) PRECOPRATICADO4,
    COALESCE(NFENTRADAITENS.PRECOPRATICADO5,0) PRECOPRATICADO5,
    COALESCE(NFENTRADAITENS.PRECOPRATICADO6,0) PRECOPRATICADO6,
    COALESCE(NFENTRADAITENS.PRECOSUGERIDO1,0) PRECOSUGERIDO1,
    COALESCE(NFENTRADAITENS.PRECOSUGERIDO2,0) PRECOSUGERIDO2,
    COALESCE(NFENTRADAITENS.PRECOSUGERIDO3,0) PRECOSUGERIDO3,
    COALESCE(NFENTRADAITENS.PRECOSUGERIDO4,0) PRECOSUGERIDO4,
    COALESCE(NFENTRADAITENS.PRECOSUGERIDO5,0) PRECOSUGERIDO5,
    COALESCE(NFENTRADAITENS.PRECOSUGERIDO6,0) PRECOSUGERIDO6,
    NFENTRADAITENS.CUSTOREPOSI,
    NFENTRADAITENS.CUSTOMEDIOATUAL,
    COALESCE(NFENTRADAITENS.CUSTOREPOSI2,0),
    NFENTRADAITENS.FRETEAVULSO,
    NFENTRADAITENS.IDNFENTRADAITEM,
    coalesce(NFENTRADAITENS.DESPFRONTPERCITEM,0),
    coalesce(NFENTRADAITENS.DESPFRONTVLRITEM,0),
    NFENTRADAITENS.CODUNIDADE,
    NFENTRADAITENS.PISVALOR,
    NFENTRADAITENS.COFINSVALOR,
    NFENTRADAITENS.PRECOCOMPRAANTERIOR,
    PRODFILHO.DESCRICAO,
    PRODFILHO.MARKUP1 MARKUPPROD1,
    PRODFILHO.MARKUP2 MARKUPPROD2,
    PRODFILHO.MARKUP3 MARKUPPROD3,
    PRODFILHO.MARKUP4 MARKUPPROD4,
    PRODFILHO.MARKUP5 MARKUPPROD5,
    PRODFILHO.MARKUP6 MARKUPPROD6,
    PRODFILHO.PRECOPRATICADO1 PRECOPRATICADOPROD1,
    PRODFILHO.PRECOPRATICADO2 PRECOPRATICADOPROD2,
    PRODFILHO.PRECOPRATICADO3 PRECOPRATICADOPROD3,
    PRODFILHO.PRECOPRATICADO4 PRECOPRATICADOPROD4,
    PRODFILHO.PRECOPRATICADO5 PRECOPRATICADOPROD5,
    PRODFILHO.PRECOPRATICADO6 PRECOPRATICADOPROD6,
    PRODFILHO.CUSTOREPOSI CUSTOREPOSIPROD,
    PRODFILHO.CUSTOMEDIO CUSTOMEDIOPROD,
    coalesce(PRODFILHO.CUSTOREPOSI2,0) CUSTOCALCULADO,
    coalesce(PRODFILHO.ALIQUOTAICMS,0),
    coalesce(PRODFILHO.IPICPRPERC,0),
    coalesce(PRODFILHO.PERC_PIS,0),
    coalesce(PRODFILHO.PERC_COFINS,0),
    coalesce(PRODFILHO.PERC_CSLL,0),
    coalesce(PRODFILHO.IMPOSTORENDA,0),
    PRODFILHO.PERCMVOUTROS,
    coalesce(PRODFILHO.ALIQCOMISSAO,0),
    coalesce(PRODFILHO.ALIQCOMISSAO_APOIO,0),
    PRODFILHO.DESPESAS_FIXAS,
    PRODFILHO.ESTQATUAL,
    coalesce(PRODFILHO.PRECOCAT,0),
    PRODFILHO.CODPRODUTO,
    coalesce(NFENTRADAITENS.DESPESAS,0),
     coalesce(NFENTRADAITENS.COMISSAO,0),
    coalesce(NFENTRADAITENS.ACRESCIMO,0)
  FROM
    NFENTRADAITENS
    JOIN PRODFILHO ON
      NFENTRADAITENS.CODPRODFILHO = PRODFILHO.CODPRODFILHO
  WHERE
    NFENTRADAITENS.CODNFENTRADA = :ECODNFENTRADA
  INTO
    :CODNFENTRADAITENS,
    :CODNFENTRADA,
    :CODPRODFILHO,
    :CODPESQUISA,
    :CODPEDCPR,
    :CODPEDCPRITENS,
    :XPEDIDO,
    :NITEMPED,
    :PRODVLR,
    :QTD,
    :TOTALPROD,
    :DESCTO_ITEM_PERC,
    :DESCTO_ITEM,
    :IPIPERC,
    :VL_IPIPERC,
    :BASE_ICMS,
    :DIFICMS,
    :PERC_REDUCAO,
    :REDUCAO_VALOR,
    :VL_DIFICMS,
    :FRETEPERCLTDA,
    :FRETEVLRLTDA,
    :DESP_PERC,
    :DESP_VALOR,
    :SEG_PERC,
    :SEG_VALOR,
    :PERC_VA,
    :VA_VALOR,
    :PREDUCAOST,
    :VREDUCAOST,
    :BASE_SUBS,
    :ALIQ_SUBS,
    :VALOR_SUBS,
    :VALORTOTAL,
    :TOTAL_NOTA,
    :MARKUP1,
    :MARKUP2,
    :MARKUP3,
    :MARKUP4,
    :MARKUP5,
    :MARKUP6,
    :PRECOPRATICADO1,
    :PRECOPRATICADO2,
    :PRECOPRATICADO3,
    :PRECOPRATICADO4,
    :PRECOPRATICADO5,
    :PRECOPRATICADO6,
    :PRECOSUGERIDO1,
    :PRECOSUGERIDO2,
    :PRECOSUGERIDO3,
    :PRECOSUGERIDO4,
    :PRECOSUGERIDO5,
    :PRECOSUGERIDO6,
    :CUSTOREPOSI,
    :CUSTOMEDIOATUAL,
    :CUSTOREPOSI2,
    :FRETEAVULSO,
    :IDNFENTRADAITEM,
    :DESPFRONTPERCITEM,
    :DESPFRONTVLRITEM,
    :CODUNIDADE,
    :LVALORPIS,
    :LVALORCOFINS,
    :PRECOCOMPRAANTERIOR,
    :DESCRICAO,
    :MARKUPPROD1,
    :MARKUPPROD2,
    :MARKUPPROD3,
    :MARKUPPROD4,
    :MARKUPPROD5,
    :MARKUPPROD6,
    :PRECOPRATICADOPROD1,
    :PRECOPRATICADOPROD2,
    :PRECOPRATICADOPROD3,
    :PRECOPRATICADOPROD4,
    :PRECOPRATICADOPROD5,
    :PRECOPRATICADOPROD6,
    :CUSTOREPOSIPROD,
    :CUSTOMEDIOPROD,
    :CUSTOCALCULADO,
    :ALIQUOTAICMS,
    :IPIPERC,
    :PERC_PIS,
    :PERC_COFINS,
    :PERC_CSLL,
    :PERC_IMPOSTORENDA,
    :PERCMVOUTROS,
    :ALIQCOMISSAO,
    :ALIQCOMISSAO_APOIO,
    :PERC_DESPESAS_FIXAS,
    :ESTOQATUAL,
    :PRECOCAT,
    :CODPRODUTO,
    :DESPESAS,
    :COMISSAO,
    :ACRESCIMO
  DO
  BEGIN
    LMARKUP1 = COALESCE(NULLIF(MARKUP1,0), MARKUPPROD1,0);
    LMARKUP2 = COALESCE(NULLIF(MARKUP2,0), MARKUPPROD2,0);
    LMARKUP3 = COALESCE(NULLIF(MARKUP3,0), MARKUPPROD3,0);
    LMARKUP4 = COALESCE(NULLIF(MARKUP4,0), MARKUPPROD4,0);
    LMARKUP5 = COALESCE(NULLIF(MARKUP5,0), MARKUPPROD5,0);
    LMARKUP6 = COALESCE(NULLIF(MARKUP6,0), MARKUPPROD6,0);
    PRECOSUGERIDO1 = 0;
    PRECOSUGERIDO2 = 0;
    PRECOSUGERIDO3 = 0;
    PRECOSUGERIDO4 = 0;
    PRECOSUGERIDO5 = 0;
    PRECOSUGERIDO6 = 0;

    SELECT
      VALOR_CALCULADO
    FROM
      STP_MKP_FORMULA_CUSTO(:PRODVLR,:PRECOCAT,:FRETEVLRLTDA,:FRETEAVULSO,:SEG_VALOR,:DESP_VALOR,:VL_IPIPERC,:VALOR_SUBS,:DESPFRONTVLRITEM,:DESCTO_ITEM,:DIFICMS, :LVALORPIS, :LVALORCOFINS)
    INTO
      CUSTO_VALOR_CALCULADO;

    SELECT
      PERC_CALCULADO
    FROM
      STP_MKP_FORMULA_CUSTOFAT(:IPIPERC,:ALIQUOTAICMS,:PERC_PIS,:PERC_COFINS,:PERC_CSLL,:PERC_IMPOSTORENDA,:PERCMVOUTROS,:ALIQCOMISSAO,:ALIQCOMISSAO_APOIO,:PERC_DESPESAS_FIXAS, 0)
    INTO
      PERC_CALCULADO;

    if (CUSTOREPOSI2 = 0) then
    begin
      CUSTOMEDIOCALCULADO = ((:CUSTO_VALOR_CALCULADO * :QTD) + (:CUSTOCALCULADO * :ESTOQATUAL)) / (:ESTOQATUAL + :QTD);
      CUSTOREPOSI2 = CUSTOMEDIOCALCULADO;
    end
    else
      CUSTOMEDIOCALCULADO = CUSTOREPOSI2;
  
    SELECT
      PRECOSUGERIDO1,
      PRECOSUGERIDO2,
      PRECOSUGERIDO3,
      PRECOSUGERIDO4,
      PRECOSUGERIDO5,
      PRECOSUGERIDO6
    FROM
      STP_MKP_FORMULA_PRECOSUGERIDO(:CUSTOMEDIOCALCULADO,:PERC_CALCULADO,:LMARKUP1,:LMARKUP2,:LMARKUP3,:LMARKUP4,:LMARKUP5,:LMARKUP6)
    INTO
      LPRECOSUGERIDO1,
      LPRECOSUGERIDO2,
      LPRECOSUGERIDO3,
      LPRECOSUGERIDO4,
      LPRECOSUGERIDO5,
      LPRECOSUGERIDO6;


    if (PRECOSUGERIDO1 = 0) then
     PRECOSUGERIDO1 = :LPRECOSUGERIDO1;
    if (PRECOSUGERIDO2 = 0) then
     PRECOSUGERIDO2 = :LPRECOSUGERIDO2;
    if (PRECOSUGERIDO3 = 0) then
     PRECOSUGERIDO3 = :LPRECOSUGERIDO3;
    if (PRECOSUGERIDO4 = 0) then
     PRECOSUGERIDO4 = :LPRECOSUGERIDO4;
    if (PRECOSUGERIDO5 = 0) then
     PRECOSUGERIDO5 = :LPRECOSUGERIDO5;
    if (PRECOSUGERIDO6 = 0) then
     PRECOSUGERIDO6 = :LPRECOSUGERIDO6;

    SELECT
      MARKUPREAL1,
      MARKUPREAL2,
      MARKUPREAL3,
      MARKUPREAL4,
      MARKUPREAL5,
      MARKUPREAL6
    FROM
      STP_MKP_FORMULA_MREAL( :CUSTOMEDIOCALCULADO,:PERC_CALCULADO,:PRECOSUGERIDO1,:PRECOSUGERIDO2,:PRECOSUGERIDO3,:PRECOSUGERIDO4,:PRECOSUGERIDO5,:PRECOSUGERIDO6)
    INTO
      MARKUPREAL1,
      MARKUPREAL2,
      MARKUPREAL3,
      MARKUPREAL4,
      MARKUPREAL5,
      MARKUPREAL6;                                                                                      
    SUSPEND;
  END
END ^

SET TERM ; ^
